name: Check Naming Convention

on:
  push:
    branches: [main]
    paths:
      - 'data/**'
  pull_request:
    branches: [main]
    paths:
      - 'data/**'

jobs:
  check_names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install pyyaml

      - name: Check file naming convention
        run: |
          cat << 'EOF' > check_naming.py
import os
import re
data_dir = 'data'
project_prefix = 'EXAMPLE'  # Set your project prefix here
pattern = re.compile(rf'^{project_prefix}_\d{{8}}_.+_v\d+\..+$')
print("Checking file naming convention EXAMPLE_YYYYMMDD_filename_version.ext in the 'data/' directory...")
invalid_files = []
if os.path.exists(data_dir):
    for filename in os.listdir(data_dir):
        if not pattern.match(filename):
            invalid_files.append(filename)
if invalid_files:
    print("Error: The following files do not follow the naming convention (EXAMPLE_YYYYMMDD_filename_version.ext):")
    for f in invalid_files:
        print(f"- {f}")
    exit(1)
else:
    print("All files in the 'data/' directory follow the naming convention.")
EOF
          python check_naming.py